### ISSUE TITLE
RayTracingMeshInstanceConfig not found

### ISSUE THREAD

**Issue by ForceConstant** [INedelcu/RayTracingDynamicMeshGeometry#1]
This for publishing this example, but it doesn't build for me, as I get multiple errors about "RayTracingMeshInstanceConfig not found" any ideas?

**Comment by INedelcu** [comment]
Fixed in a7a6ac3722d90938ab37173e790157056c1a4e70

**Comment by ForceConstant** [comment]
Still error: I am using 2021.3.4

![image](https://user-images.githubusercontent.com/26015318/208647743-992bea18-a175-4bc5-9c5e-c6bbcff82d91.png)

**Comment by INedelcu** [comment]
https://github.com/INedelcu/RayTracingDynamicMeshGeometry#prerequisites

**Comment by INedelcu** [comment]
It needs Unity 2023.1.0a3+.

**Comment by ForceConstant** [comment]
Wow so only alpha, not even latest beta?

**Comment by INedelcu** [comment]
It will work with any version starting with 2023.0.a3 where the feature was introduced so it will be available in 2023.0.b1 for example.
